### ISSUE TITLE
Entered mail-id hiding

### ISSUE THREAD

**Issue by KailashPatil** [harp/harpjs.com#43]
Not able to see the entered mail-id, while subscribing for newsletter in 'Stay static' block. Issue is with padding.

URL : http://harpjs.com/blog/v0-13-0-upgrading-node
Browser : Firefox 38.0

**Comment by kennethormandy** [comment]
Thanks! Apparently it’s [some weird Bootstrap thing](http://stackoverflow.com/questions/24448991/input-padding-cutting-out-text-in-firefox). Fixed now.
