### ISSUE TITLE
Unable to fire up server

### ISSUE THREAD

**Issue by darokel** [harp/harpjs.com#51]
I could be missing something but I just fresh installed `node.js -v 0.12.7` and tried:

1) `npm install -g harp`
2) `harp init project`
3) `harp server`

Result:

```bash
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
  at exports._errnoException (util.js:746:11)
  at Server._listen2 (net.js:1156:14)
  at listen (net.js:1182:10)
  at net.js:1280:9
  at dns.js:85:18
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3
```

I'm on OSX Yosemite v10.10.4

**Comment by kennethormandy** [comment]
Looks like you already have something running on Harp’s default port, `9000`. You can find it like this: http://harpjs.com/docs/environment/port-conflicts or run Harp on a different port: `harp server --port 9001`

Let me know if that fixes it!

**Comment by darokel** [comment]
Yes it did, thanks!
