### ISSUE TITLE
Update "Deploying on Heroku" to use the official Heroku nodejs buildpack

### ISSUE THREAD

**Issue by edmorley** [harp/harpjs.com#53]
The instructions currently suggest using this custom buildpack, which is now deprecated:
https://github.com/zeke/harp-buildpack#deprecated

The deprecation message suggests using the official Heroku nodejs buildpack - it would be good if we could update the docs to that effect:
http://harpjs.com/docs/deployment/heroku

Thanks :-)

**Comment by kennethormandy** [comment]
Thanks, and sorry if it caused any confusion. Admittedly, it hasn’t been something we’ve been able to make high-priority. We’d definitely accept a PR for this if you want to take it on. Here’s the page: https://github.com/harp/harpjs.com/blob/9dae7fe22bef2ceeb1f1e6978f1fa5a35d07d8f9/public/docs/deployment/heroku.md

**Comment by kennethormandy** [comment]
We should even be able to steal it from Zeke’s README https://github.com/zeke/harp-buildpack
